// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQ-gB4FgMe_IRzKEllFUg1_if_RT-l1E',
    appId: '1:1016508453989:web:8a17aafe9f13a9d29f628c',
    messagingSenderId: '1016508453989',
    projectId: 'e-commerce-1cd12',
    authDomain: 'e-commerce-1cd12.firebaseapp.com',
    storageBucket: 'e-commerce-1cd12.appspot.com',
    measurementId: 'G-03899VX4SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxiUoJgX1UQa8jphkwpBETJlN4gwTWDA',
    appId: '1:1016508453989:android:c9fb298139415fcc9f628c',
    messagingSenderId: '1016508453989',
    projectId: 'e-commerce-1cd12',
    storageBucket: 'e-commerce-1cd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmMHIfmq2laTSCwbPj3BI7l7EMQwb_SA',
    appId: '1:1016508453989:ios:13a17fed7bccaaee9f628c',
    messagingSenderId: '1016508453989',
    projectId: 'e-commerce-1cd12',
    storageBucket: 'e-commerce-1cd12.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmMHIfmq2laTSCwbPj3BI7l7EMQwb_SA',
    appId: '1:1016508453989:ios:9f605205b08d35b89f628c',
    messagingSenderId: '1016508453989',
    projectId: 'e-commerce-1cd12',
    storageBucket: 'e-commerce-1cd12.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
